version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "550:3000"
    restart: always
    volumes:
      - .:/app  
# đã thành công reload được 1 phần add nhưng nó chưa hot reload được

