version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "550:3000"
    restart: always
    volumes:
      - .:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=550 # The mapped port on your host machine  


