version: '3'
services:
  react:
    build:
      context: .
      dockerfile: 2Dockerfile
    restart: always
    volumes:
      - .:/app  
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    restart: always
    # volumes:
      # - ./app/build:/usr/share/nginx/html


// do là ánh xạ 2 chiều nên nếu ta run build ở bên trong thì cũng sẽ build ở bên ngoài, oki      
      