version: '3'
services:
  nginx:
    image: nginx:latest
    ports: 
      - "70:80"
    restart: always
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    # environment:
    #   - FAST_REFRESH=false
    #   - WDS_SOCKET_PORT=40 # The mapped   